export const investmentOpportunities = [
    {
      image: "https://photos.zillowstatic.com/fp/a1587d5bae3b58dfa2c97d1101138143-cc_ft_768.webp",
      title: "Verified Real Estate Investment",
      annualReturn: "30% p.a",
      description: "Return on investment",
      investmentAmount: 10000,
      investorsCount: 19128,
      duration: "Per Unit",
      status: "Invest Now",
    },
    {
      image: "https://photos.zillowstatic.com/fp/33abe06f30f128aecf30f7e1a75507bf-cc_ft_1536.webp",
      title: "Corporate Debt Notes Series",
      annualReturn: "11.1% p.a",
      description: "Returns in 6 months",
      investmentAmount: 5000,
      investorsCount: 709,
      duration: "Per Unit",
      status: "Sold Out",
    },
    {
      image: "https://photos.zillowstatic.com/fp/a211ef3ebf5bf1a7742e7cfd53e09a58-cc_ft_1536.webp",
      title: "Venture Capital Fund",
      annualReturn: "25% p.a",
      description: "High growth potential",
      investmentAmount: 15000,
      investorsCount: 5321,
      duration: "Per Unit",
      status: "Invest Now",
    },
    {
      image: "https://photos.zillowstatic.com/fp/c2672a25a83b9689aa1c5b53e4a5bf2a-cc_ft_768.webp",
      title: "Startup Equity Investment",
      annualReturn: "20% p.a",
      description: "Equity stake in promising startups",
      investmentAmount: 8000,
      investorsCount: 432,
      duration: "Per Unit",
      status: "Invest Now",
    },
    {
      image: "https://photos.zillowstatic.com/fp/7375bdd70e931851043daff4a4c51080-cc_ft_768.webp",
      title: "Land Acquisition Opportunity",
      annualReturn: "15% p.a",
      description: "Steady appreciation of land",
      investmentAmount: 12000,
      investorsCount: 1024,
      duration: "Per Unit",
      status: "Sold Out",
    },
    {
      image: "https://photos.zillowstatic.com/fp/11fd1011029ba7cd0b4f66e6783baaf5-cc_ft_768.webp",
      title: "Commercial Property Investment",
      annualReturn: "28% p.a",
      description: "Rental income and capital gains",
      investmentAmount: 20000,
      investorsCount: 8421,
      duration: "Per Unit",
      status: "Invest Now",
    },
    {
      image: "https://photos.zillowstatic.com/fp/9a8b69f9ab2240b532e226dd22f48aad-cc_ft_768.webp",
      title: "Property Development Project",
      annualReturn: "22% p.a",
      description: "Pre-sale investment opportunity",
      investmentAmount: 18000,
      investorsCount: 651,
      duration: "Per Unit",
      status: "Invest Now",
    },
    {
      image: "https://photos.zillowstatic.com/fp/42cc799e4a0cb9d176d568e857c5b3e7-cc_ft_1536.webp",
      title: "Infrastructure Bond",
      annualReturn: "10% p.a",
      description: "Stable long-term bond",
      investmentAmount: 5000,
      investorsCount: 3120,
      duration: "Per Unit",
      status: "Sold Out",
    },
    {
      image: "https://photos.zillowstatic.com/fp/1711b0c26c20f0ce3f61c21de358492b-cc_ft_768.webp",
      title: "Real Estate Finance Fund",
      annualReturn: "18% p.a",
      description: "Returns from mortgage financing",
      investmentAmount: 9000,
      investorsCount: 2901,
      duration: "Per Unit",
      status: "Invest Now",
    },
    {
      image: "https://photos.zillowstatic.com/fp/42ccd7f33830d1e1ac786666d9d9042d-cc_ft_1536.webp",
      title: "Private Equity Investment",
      annualReturn: "35% p.a",
      description: "Exclusive private equity deals",
      investmentAmount: 25000,
      investorsCount: 1500,
      duration: "Per Unit",
      status: "Invest Now",
    },
    {
      image: "https://photos.zillowstatic.com/fp/ee7bce8869a2d85a570b83adcce7a7ec-cc_ft_768.webp",
      title: "Balanced Investment Fund",
      annualReturn: "12% p.a",
      description: "Diversified portfolio",
      investmentAmount: 7000,
      investorsCount: 980,
      duration: "Per Unit",
      status: "Invest Now",
    },
    {
      image: "https://photos.zillowstatic.com/fp/9ce83b1432e205fd780b4a0662211024-cc_ft_768.webp",
      title: "Green Energy Investment",
      annualReturn: "16% p.a",
      description: "Sustainable energy projects",
      investmentAmount: 11000,
      investorsCount: 2000,
      duration: "Per Unit",
      status: "Sold Out",
    },
    {
      image: "https://photos.zillowstatic.com/fp/3d18524529d5594dbf327d673796c61c-p_e.webp",
      title: "Crypto Asset Fund",
      annualReturn: "40% p.a",
      description: "High volatility, high returns",
      investmentAmount: 30000,
      investorsCount: 6500,
      duration: "Per Unit",
      status: "Invest Now",
    },
    {
      image: "https://photos.zillowstatic.com/fp/74951a340ee124987b9876d915b672e5-p_e.webp",
      title: "Forex Trading Fund",
      annualReturn: "14% p.a",
      description: "Currency market opportunities",
      investmentAmount: 6000,
      investorsCount: 1400,
      duration: "Per Unit",
      status: "Invest Now",
    },
    {
      image: "https://photos.zillowstatic.com/fp/70b07e8a37a952620d380b8d8e8dd9ca-p_e.webp",
      title: "Commodities Investment",
      annualReturn: "13% p.a",
      description: "Invest in precious metals and commodities",
      investmentAmount: 7500,
      investorsCount: 875,
      duration: "Per Unit",
      status: "Sold Out",
    },
    {
      image: "https://photos.zillowstatic.com/fp/7fdde53ef39ccfeac054f14254796987-p_e.webp",
      title: "Sustainable Agriculture Fund",
      annualReturn: "17% p.a",
      description: "Invest in sustainable farming",
      investmentAmount: 9500,
      investorsCount: 1020,
      duration: "Per Unit",
      status: "Invest Now",
    },
    {
      image: "https://photos.zillowstatic.com/fp/b0f5efeff0d00ab345da554c6e6bdc3f-p_e.webp",
      title: "Tourism & Hospitality Investment",
      annualReturn: "19% p.a",
      description: "Returns from tourism projects",
      investmentAmount: 8500,
      investorsCount: 450,
      duration: "Per Unit",
      status: "Invest Now",
    },
    {
      image: "https://photos.zillowstatic.com/fp/ee85cd48270c8ed02a77f1ae4928b8b2-p_e.webp",
      title: "Healthcare Investment Opportunity",
      annualReturn: "23% p.a",
      description: "Invest in healthcare innovations",
      investmentAmount: 13000,
      investorsCount: 770,
      duration: "Per Unit",
      status: "Sold Out",
    },
    {
      image: "https://photos.zillowstatic.com/fp/2987f3e93df5687dbff12959bc6b19bb-cc_ft_1536.webp",
      title: "Education Sector Investment",
      annualReturn: "15% p.a",
      description: "Returns from educational projects",
      investmentAmount: 8000,
      investorsCount: 980,
      duration: "Per Unit",
      status: "Invest Now",
    },
    {
      image: "https://photos.zillowstatic.com/fp/24c8c64df91fa240c5292a8bb7503bb6-p_e.webp",
      title: "Technology Investment Fund",
      annualReturn: "27% p.a",
      description: "Invest in tech startups",
      investmentAmount: 22000,
      investorsCount: 4200,
      duration: "Per Unit",
      status: "Invest Now",
    }
  ];